"""业务存储的最小接口；后续替换 SQLite 不改变调用方领域模型。"""

from typing import Protocol

from media_operations.schemas import (
    AccountBrief, AccountCreate, AgentRun, AgentTask, AgentTaskResult,
    ContentStrategy, Payload, RunCreate, RunEvent, StrategyCreate, TaskError,
)


class OperationsStore(Protocol):
    def create_account(self, config: AccountCreate, strategy: StrategyCreate | None = None) -> AccountBrief: ...
    def get_account(self, account_id: str) -> AccountBrief: ...
    def update_account(self, account_id: str, config: AccountCreate, *, expected_version: int) -> AccountBrief: ...
    def get_strategy(self, account_id: str, version: int | None = None) -> ContentStrategy: ...
    def update_strategy(self, account_id: str, config: StrategyCreate, *, expected_version: int) -> ContentStrategy: ...
    def create_run(self, account_id: str, request: RunCreate) -> AgentRun: ...
    def get_run(self, account_id: str, run_id: str) -> AgentRun: ...
    def claim_next_run(self) -> AgentRun | None: ...
    def list_tasks(self, account_id: str, run_id: str) -> list[AgentTask]: ...
    def list_events(self, account_id: str, run_id: str, *, after_seq: int = 0, limit: int = 100) -> list[RunEvent]: ...
    def start_task(self, account_id: str, run_id: str, task_id: str) -> AgentTask: ...
    def complete_task(self, account_id: str, run_id: str, task_id: str, result: AgentTaskResult[Payload]) -> AgentTask: ...
    def fail_task(self, account_id: str, run_id: str, task_id: str, error: TaskError) -> AgentRun: ...
    def finish_run(self, account_id: str, run_id: str) -> AgentRun: ...
    def cancel_run(self, account_id: str, run_id: str) -> AgentRun: ...

